### ISSUE TITLE
bemapiset.h

### ISSUE THREAD

**Issue by not-lob** [microsoftarchive/KinectCommonBridge#10]
Looking to compile the most recent version but can't seem to track down bemapiset.h which is included from comsmartptr.h. Assuming I'm missing a prereq of some kind. Any pointers would be much appreciated.

Thanks,
John

**Comment by mkostin** [comment]
Thanks for feedback, John.

Common location for this header is: 
`C:\Program Files (x86)\Windows Kits\X.Y\Include\um\bemapiset.h`
where `X.Y` is the version available on your machine (e.g. 8.0 or 8.1). Please verify that you've fulfilled all prerequisites as stated in the [readme instructions](https://github.com/MSOpenTech/KinectCommonBridge#requirements).

**Comment by not-lob** [comment]
Got it. Thanks!
