### ISSUE TITLE
Bug in KCBGetAllFrameData()

### ISSUE THREAD

**Issue by newstzpz** [microsoftarchive/KinectCommonBridge#14]
In lines 879, 888, 904, 913, 922 and 931 of KCBv2Lib.cpp, a reference to the variable TimeStamp, instead of the variable itself, should be passed to get_RelativeTime(). For example:

 // get timestamp
CHECK_HR(hr = pBodyFrame->get_RelativeTime(reinterpret_cast<TIMESPAN*>(&pstBodyFrame->TimeStamp)));

**Comment by mkostin** [comment]
Thanks again @newstzpz for you input and [previous notes](https://github.com/MSOpenTech/KinectCommonBridge/issues/13). Please don't hesitate to provide  pull request with a fix if you face an issue and have already fixed it on your side. Fixed, closing.
