### ISSUE TITLE
'NuiApi.h': No such file error during build

### ISSUE THREAD

**Issue by ADNewbie** [microsoftarchive/KinectCommonBridge#15]
Apologies for cross posting.
I get 'NuiApi.h': No such file error during build (VS 13, Windows8.1), which I assume relate to configuration settings. Are the clear configuration settings anywhere? I tried to follow and adapt instructions here: https://github.com/joshuajnoble/ofxKinectCommonBridge to no avail. 
Any suggestions?

**Comment by mkostin** [comment]
Hi @ADNewbie, assuming you're using [dev](https://github.com/MSOpenTech/KinectCommonBridge/tree/dev) or [master](https://github.com/MSOpenTech/KinectCommonBridge/tree/master) branch that are targeting Kinect v1.8 SDK, you can find NuiApi.h in  `%KINECTSDK10_DIR%\inc` directory (e.g. `c:\Program Files\Microsoft SDKs\Kinect\v1.8\inc\`). See details on MSDN [here](http://msdn.microsoft.com/en-us/library/hh855360.aspx#ID4ESBAC).

For Kinect 2.0 SDK ([2.0 branch](https://github.com/MSOpenTech/KinectCommonBridge/tree/2.0)) please don't forget to use `$(KINECTSDK20_DIR)inc`.

**Comment by ADNewbie** [comment]
Thanks mkostin, 
Edit: Problem solved (I think). For others sake, I was using master branch instead of 2.0 branch.
I'll close the issue.
