### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by vinjn** [microsoftarchive/KinectCommonBridge#23]

**Comment by ghost** [comment]
Please be specific about what you need if you are going to open an issue. Bug reports, concrete suggestions, and code contributions are always welcome.

**Comment by vinjn** [comment]
I'd like to know your roadmap of this project.

Examples for v2 is far from complete.
Lots of features are also missing in v2, e.g. face tracking, Kinect Fushion.
Are you still going to implement them?
