### ISSUE TITLE
Readme doesn't mention Face Tracking Lib

### ISSUE THREAD

**Issue by elliotwoods** [microsoftarchive/KinectCommonBridge#4]
Face Tracking Lib is a requirement for building
but isn't mentioned in the readme
ideally should have a link like the other requirements

**Comment by mkostin** [comment]
Fixed with ecaf2620b5db3dac09cc53dc2bb102260feb10ed. 
Please take a look at [this README section](https://github.com/MSOpenTech/KinectCommonBridge#more-advanced-functionality-face-tracking-and-voice-recognition). It now mentions FTL and usage requirements. 
Thanks for reporting!
