### ISSUE TITLE
Should be able to compile using free Visual Studio Express

### ISSUE THREAD

**Issue by obviousjim** [microsoftarchive/KinectCommonBridge#8]
Currently KCB requires:
 #include <atlbase.h>

Which excludes Visual Studio Express. In the spirit of openness I think that we should allow this to be built using a free IDE.

**Comment by stammen** [comment]
How would a developer build x64 OpenFrameworks projects?

**Comment by obviousjim** [comment]
Hi Dale, 

Not sure that this issue is directly related to x64 -- but to answer your question we are currently using this experimental x64 branch:
https://github.com/prisonerjohn/openFrameworks/tree/0.8.0_64

And there are several others floating around too.

**Comment by stammen** [comment]
My point is that it is not possible to develop or build x64 OpenFrameworks projects without x64 capable version of Visual Studio. A user with VS Express cannot work with x64 version of OF.

**Comment by obviousjim** [comment]
Hi we just confirmed on this side that you can in fact build x64 on VS Express, so the issue still stands.

**Comment by stammen** [comment]
Thanks. Are you using VS Express 2012?

**Comment by obviousjim** [comment]
yes

**Comment by stammen** [comment]
It looks like we would have to rewrite KCB to not use CComPtr as that is not supported in Express versions.

**Comment by obviousjim** [comment]
(being facetious) or start giving away VS for free :) This recent development of giving away the OS, maybe it's possible to reconsider paying for IDEs too?

**Comment by stammen** [comment]
We are working on updating KCB to compile with Visual Studio Express.

**Comment by mkostin** [comment]
KCB version compilable using Visual Studio Express ([VSe2013](http://www.microsoft.com/en-us/download/details.aspx?id=40787) was used) can be now found in [ccomptr-8](https://github.com/MSOpenTech/KinectCommonBridge/tree/ccomptr-8) branch.
